# Generated by Django 3.2 on 2024-09-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='upc',
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
